# Generated by Django 5.1.1 on 2024-11-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_alter_follow_follower'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='prevent_self_follow',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
