# Generated by Django 5.1.1 on 2024-11-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
