# Generated by Django 5.1.1 on 2024-11-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_follow_unique_follow_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
