# Generated by Django 5.1.1 on 2024-10-20 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_reply_count'),
        ('snippets', '0007_alter_snippet_token'),
        ('votes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('snippet__isnull', False), ('comment__isnull', True)), models.Q(('snippet__isnull', True), ('comment__isnull', False)), _connector='OR'), name='vote_snippet_or_commnet'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('snippet__isnull', False)), fields=('user', 'snippet'), name='unique_user_snippet'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment'), name='unique_user_comment'),
        ),
    ]
