# Generated by Django 5.1.1 on 2024-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Please provide an email address.', 'unique': 'This email is already in use.'}, max_length=254, unique=True),
        ),
    ]
