# Generated by Django 5.1.1 on 2024-10-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_post',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
