# Generated by Django 5.1.1 on 2024-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='media/profile/profile_avatar.jpg', upload_to='profile/'),
        ),
    ]
