# Generated by Django 5.1.1 on 2024-10-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='snippet_type',
            field=models.CharField(default='unknown', max_length=15),
        ),
    ]
