# Generated by Django 5.1.1 on 2024-10-07 15:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_rename_snippet_type_snippet_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
