# Generated by Django 5.1.1 on 2024-10-09 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_snippet_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
