# Generated by Django 5.1.1 on 2024-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_snippet_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
