# Generated by Django 5.1.1 on 2024-11-26 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_snippet_comment_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='snippet',
            constraint=models.CheckConstraint(condition=models.Q(('comment_count__gte', 0)), name='comment_count_non_negative'),
        ),
    ]
