# Generated by Django 5.1.1 on 2024-11-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_snippet_comment_count_non_negative'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='snippet',
            name='comment_count_non_negative',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='comment_count',
        ),
    ]
