# Generated by Django 5.1.1 on 2024-11-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_remove_snippet_comment_count_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
