# Generated by Django 5.1.1 on 2024-12-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_snippet_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='upvotes',
        ),
    ]
