# Generated by Django 5.1.1 on 2024-12-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_remove_snippet_comment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snippet',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snippet',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
